INSERT INTO categories (name)
VALUES 
    ('Astronomy'),
    ('Biology'),
    ('Chemistry'),
    ('Geology'),
    ('Computer Science');

INSERT INTO questions (question, answer, category)
VALUES 
    -- Astronomy
    ('What is the sun?', 'A star', 'Astronomy'),
    ('What are the names of the planets?', 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune', 'Astronomy'),
    ('What is the moon?', 'Earth''s natural satellite', 'Astronomy'),
    ('What is the closest planet to the sun?', 'Mercury', 'Astronomy'),
    ('How many planets are in the solar system?', 'Eight', 'Astronomy'),
    ('What is the largest planet?', 'Jupiter', 'Astronomy'),
    ('What planet is known as the red planet?', 'Mars', 'Astronomy'),
    ('What is a comet?', 'A ball of ice and dust', 'Astronomy'),
    ('What galaxy is Earth in?', 'The Milky Way', 'Astronomy'),
    ('What planet is known for its rings?', 'Saturn', 'Astronomy'),
    ('What is the hottest planet?', 'Venus', 'Astronomy'),
    ('What is a shooting star?', 'A meteor', 'Astronomy'),
    ('What do stars produce?', 'Light and heat', 'Astronomy'),
    ('What planet is known as the blue planet?', 'Earth', 'Astronomy'),
    ('What is the smallest planet?', 'Mercury', 'Astronomy'),
    ('What is the name of our galaxy?', 'The Milky Way', 'Astronomy'),
    ('What is the largest moon of Jupiter?', 'Ganymede', 'Astronomy'),

    -- Biology
    ('What does DNA stand for?', 'Deoxyribonucleic acid', 'Biology'),
    ('What is a cell?', 'The smallest unit of life', 'Biology'),
    ('What do plants need to grow?', 'Sunlight, water, and soil', 'Biology'),
    ('What is photosynthesis?', 'Process plants use to make food', 'Biology'),
    ('What are herbivores?', 'Animals that eat plants', 'Biology'),
    ('What is the main job of the heart?', 'To pump blood', 'Biology'),
    ('What do humans breathe in?', 'Oxygen', 'Biology'),
    ('What is a carnivore?', 'An animal that eats meat', 'Biology'),
    ('What do bones do?', 'Support the body', 'Biology'),
    ('What part of the body controls everything?', 'The brain', 'Biology'),
    ('What is the largest organ?', 'The skin', 'Biology'),
    ('What is a habitat?', 'Where an animal lives', 'Biology'),
    ('What is an omnivore?', 'An animal that eats plants and meat', 'Biology'),
    ('What are mammals?', 'Animals that have hair and produce milk', 'Biology'),
    ('What do plants breathe in?', 'Carbon dioxide', 'Biology'),
    ('What is the basic unit of life?', 'The cell', 'Biology'),

    -- Chemistry
    ('What charge does a proton have?', 'Positive', 'Chemistry'),
    ('What charge does an electron have?', 'Negative', 'Chemistry'),
    ('What is H2O?', 'Water', 'Chemistry'),
    ('What is the chemical symbol for oxygen?', 'O', 'Chemistry'),
    ('What element does "C" stand for?', 'Carbon', 'Chemistry'),
    ('What is NaCl?', 'Salt', 'Chemistry'),
    ('What is the center of an atom?', 'Nucleus', 'Chemistry'),
    ('What is the periodic table?', 'Chart of elements', 'Chemistry'),
    ('What is a molecule?', 'Two or more atoms bonded together', 'Chemistry'),
    ('What is a mixture?', 'Combination of substances', 'Chemistry'),
    ('What gas do we exhale?', 'Carbon dioxide', 'Chemistry'),
    ('What is the chemical symbol for gold?', 'Au', 'Chemistry'),
    ('What is a solution?', 'A mixture of solute and solvent', 'Chemistry'),
    ('What is CO2?', 'Carbon dioxide', 'Chemistry'),
    ('What is the atomic number of hydrogen?', 'One', 'Chemistry'),
    ('What does pH measure?', 'Acidity or alkalinity', 'Chemistry'),

    -- Geology
    ('What is the outermost layer of Earth?', 'The crust', 'Geology'),
    ('What are the three types of plate boundaries?', 'Divergent, convergent, and transform', 'Geology'),
    ('What is a volcano?', 'A mountain that erupts lava', 'Geology'),
    ('What is a mineral?', 'A solid natural substance', 'Geology'),
    ('What is erosion?', 'Wearing away of rocks', 'Geology'),
    ('What is the hardest mineral?', 'Diamond', 'Geology'),
    ('What is a fossil?', 'Remains of ancient life', 'Geology'),
    ('What is the study of rocks?', 'Geology', 'Geology'),
    ('What is an earthquake?', 'Shaking of the ground', 'Geology'),
    ('What is magma?', 'Molten rock inside Earth', 'Geology'),
    ('What is a glacier?', 'A large mass of moving ice', 'Geology'),
    ('What are tectonic plates?', 'Large pieces of Earth''s crust', 'Geology'),
    ('What is a tsunami?', 'A large ocean wave', 'Geology'),
    ('What is a sedimentary rock?', 'Rock formed from sediments', 'Geology'),
    ('What is the Earth''s core made of?', 'Iron and nickel', 'Geology'),
    ('What is the most common rock on Earth?', 'Basalt', 'Geology'),

    -- Computer Science
    ('What does HTTP stand for?', 'HyperText Transfer Protocol', 'Computer Science'),
    ('What does CPU stand for?', 'Central Processing Unit', 'Computer Science'),
    ('What is a keyboard used for?', 'Typing', 'Computer Science'),
    ('What does RAM stand for?', 'Random Access Memory', 'Computer Science'),
    ('What does USB stand for?', 'Universal Serial Bus', 'Computer Science'),
    ('What is an algorithm?', 'A set of instructions', 'Computer Science'),
    ('What is software?', 'Programs that run on computers', 'Computer Science'),
    ('What is the Internet?', 'A network of connected computers', 'Computer Science'),
    ('What does a mouse do?', 'Moves the pointer on screen', 'Computer Science'),
    ('What is a byte?', 'A unit of data', 'Computer Science'),
    ('What is a search engine?', 'A tool to find information online', 'Computer Science'),
    ('What is coding?', 'Writing instructions for a computer', 'Computer Science'),
    ('What is an app?', 'A software program', 'Computer Science'),
    ('What is a web browser?', 'A tool to access websites', 'Computer Science'),
    ('What is a file?', 'A document or data storage unit', 'Computer Science'),
    ('What is a bit?', 'Smallest unit of data', 'Computer Science');
